feat: More useful error messages for protocol parameters & components
bihealth/altamisa pull request #106
Opened 2023-11-03 17:02 UTC by sellth

Now reports protocol in question lengths so the user can easily spot the mistake. Limitations: Does not report the affected Study.

2024-01-15 12:58 UTC, holtgrewe requested changes
see other comment

2024-01-16 13:33 UTC, sellth commented
@holtgrewe type hints added

2024-01-18 13:49 UTC, holtgrewe commented
@sellth next time, re-request review then this appears as "fresh work" to me in the UI

2024-01-18 13:50 UTC, holtgrewe approved these changes

2024-01-18 13:50 UTC, merged