ci: switch to codecov rather than codacy (#110)
bihealth/altamisa pull request #111
Opened 2024-01-12 11:46 UTC by holtgrewe

2024-01-12 15:17 UTC, sellth requested changes
We probably only need one Codedov badge.

2024-01-12 15:17 UTC, sellth commented on README.md
> +[![codecov](https://codecov.io/gh/bihealth/altamisa/graph/badge.svg?token=R5GXUKCUYJ)](https://codecov.io/gh/bihealth/altamisa)
duplicate

2024-01-15 07:07 UTC, holtgrewe commented on README.md
> +[![codecov](https://codecov.io/gh/bihealth/altamisa/graph/badge.svg?token=R5GXUKCUYJ)](https://codecov.io/gh/bihealth/altamisa)
done

2024-01-15 09:40 UTC, sellth approved these changes
LGTM

2024-01-15 12:42 UTC, merged